In [1]:
# bot_v1_signals
# Выдача сигналов без торговли
import pandas as pd
import os
import time
from dotenv import load_dotenv
from pybit.unified_trading import HTTP
from config import STRATEGY_PARAMS, SYMBOL, TIMEFRAME
from strategy import generating_signals

load_dotenv()

# Настройка прокси
proxy_url = f"http://{os.getenv('PROXY_LOGIN')}:{os.getenv('PROXY_PASSWORD')}@{os.getenv('PROXY_HOST')}:{os.getenv('PROXY_PORT')}"
print(proxy_url)
os.environ['HTTP_PROXY'] = proxy_url
os.environ['HTTPS_PROXY'] = proxy_url

# Настройка подключения к Байбит
session = HTTP(
    testnet=True,
    api_key=os.getenv('BYBIT_API_KEY'),
    api_secret=os.getenv('BYBIT_SECRET')
)
public_session = HTTP(testnet=True, timeout=30)

def fetch_klines(limit=200):
    klines = public_session.get_kline(
        category='spot',
        symbol = SYMBOL,
        interval = TIMEFRAME,
        limit = limit)
    ticker_df = pd.DataFrame(klines.get('result').get('list'), columns=['datetime', 'open', 'high', 'low', 'close', 'volume', 'turnover'])
    ticker_df['datetime'] = pd.to_datetime(ticker_df['datetime'].astype('int64'), unit='ms')
    ticker_df.set_index('datetime', inplace=True)
    ticker_df = ticker_df.astype('float64')
    ticker_df = ticker_df.sort_index()

    return ticker_df

def main():
    print("🤖 Робот запущен (режим сигналов)")
    print(f"Символ: {SYMBOL}")
    print(f"Таймфрейм: {TIMEFRAME}")
    print(f"Параметры: {STRATEGY_PARAMS}")
    print("="*50)

    last_signal = None
    
    while True:
        try:
            df = fetch_klines(limit=200)
            signal, sl, tp = generating_signals(df, STRATEGY_PARAMS)
            if signal == 1 and last_signal != 1:
                print(f"🟢 LONG сигнал! Цена: {df['close'].iloc[-1]:.2f}")
                last_signal = 1
            elif signal == -1 and last_signal != -1:
                print(f"🔴 SHORT сигнал! Цена: {df['close'].iloc[-1]:.2f}")
                дфые_ышптфд = -1
            elif signal == 0:
                pass
    
            time.sleep(60)

        except KeyboardInterrupt:
            print("\n🛑 Робот остановлен")
            break
        except Exception as e:
            print(f"❌ Ошибка: {e}")
            time.sleep(60)
        
if __name__ == "__main__":
    main()

http://pydA627P:CPcsSL91@154.219.29.120:63596
🤖 Робот запущен (режим сигналов)
Символ: BTCUSDT
Таймфрейм: D
Параметры: {'lookback': 90, 'range_days': 3, 'volatility': 0.05, 'reward_risk': 1}
==================================================

                open      high       low     close        volume      turnover
datetime
2025-11-28  90671.64  97034.36  87147.19  90851.61  4.234554e+02  3.982736e+07
2025-11-29  90851.61  92686.56  85989.45  90827.26  1.169327e+02  1.061767e+07
2025-11-30  90827.26  96200.00  89932.60  95992.31  3.285488e+02  3.061314e+07
2025-12-01  95992.31  96268.64  95767.52  95767.52  5.168455e+01  4.954266e+06
2025-12-02  95767.52  96268.64  78163.90  87713.20  1.847650e+06  1.642927e+11
...              ...       ...       ...       ...           ...           ...
2026-06-11  61825.00  61825.00  61024.10  61755.80  2.858224e+02  1.753588e+07
2026-06-12  61755.80  63730.80  61755.80  63551.20  4.039001e+02  2.545399e+07
2026-06-13  63551.20  64625.20  63431.60  64495.50  4.442794e+02  2.840637e+07
2026-06-14  64495.50  65520.40  63879.20  64820.20  3.735011e+02  2.415846e+07
2026-06-15  64820.20  66117.20  64774.40  66117.20  1.955217e+02  1.281463e+07

[200 rows x 6 columns]

                open      high       low     close        volume      turnover
datetime
2025-11-28  90671.64  97034.36  87147.19  90851.61  4.234554e+02  3.982736e+07
2025-11-29  90851.61  92686.56  85989.45  90827.26  1.169327e+02  1.061767e+07
2025-11-30  90827.26  96200.00  89932.60  95992.31  3.285488e+02  3.061314e+07
2025-12-01  95992.31  96268.64  95767.52  95767.52  5.168455e+01  4.954266e+06
2025-12-02  95767.52  96268.64  78163.90  87713.20  1.847650e+06  1.642927e+11
...              ...       ...       ...       ...           ...           ...
2026-06-11  61825.00  61825.00  61024.10  61755.80  2.858224e+02  1.753588e+07
2026-06-12  61755.80  63730.80  61755.80  63551.20  4.039001e+02  2.545399e+07
2026-06-13  63551.20  64625.20  63431.60  64495.50  4.442794e+02  2.840637e+07
2026-06-14  64495.50  65520.40  63879.20  64820.20  3.735011e+02  2.415846e+07
2026-06-15  64820.20  66117.20  64774.40  66117.20  1.955217e+02  1.281463e+07

[200 rows x 6 columns]

                open      high       low     close        volume      turnover
datetime
2025-11-28  90671.64  97034.36  87147.19  90851.61  4.234554e+02  3.982736e+07
2025-11-29  90851.61  92686.56  85989.45  90827.26  1.169327e+02  1.061767e+07
2025-11-30  90827.26  96200.00  89932.60  95992.31  3.285488e+02  3.061314e+07
2025-12-01  95992.31  96268.64  95767.52  95767.52  5.168455e+01  4.954266e+06
2025-12-02  95767.52  96268.64  78163.90  87713.20  1.847650e+06  1.642927e+11
...              ...       ...       ...       ...           ...           ...
2026-06-11  61825.00  61825.00  61024.10  61755.80  2.858224e+02  1.753588e+07
2026-06-12  61755.80  63730.80  61755.80  63551.20  4.039001e+02  2.545399e+07
2026-06-13  63551.20  64625.20  63431.60  64495.50  4.442794e+02  2.840637e+07
2026-06-14  64495.50  65520.40  63879.20  64820.20  3.735011e+02  2.415846e+07
2026-06-15  64820.20  66117.20  64774.40  66117.20  1.955218e+02  1.281464e+07

[200 rows x 6 columns]

                open      high       low     close        volume      turnover
datetime
2025-11-28  90671.64  97034.36  87147.19  90851.61  4.234554e+02  3.982736e+07
2025-11-29  90851.61  92686.56  85989.45  90827.26  1.169327e+02  1.061767e+07
2025-11-30  90827.26  96200.00  89932.60  95992.31  3.285488e+02  3.061314e+07
2025-12-01  95992.31  96268.64  95767.52  95767.52  5.168455e+01  4.954266e+06
2025-12-02  95767.52  96268.64  78163.90  87713.20  1.847650e+06  1.642927e+11
...              ...       ...       ...       ...           ...           ...
2026-06-11  61825.00  61825.00  61024.10  61755.80  2.858224e+02  1.753588e+07
2026-06-12  61755.80  63730.80  61755.80  63551.20  4.039001e+02  2.545399e+07
2026-06-13  63551.20  64625.20  63431.60  64495.50  4.442794e+02  2.840637e+07
2026-06-14  64495.50  65520.40  63879.20  64820.20  3.735011e+02  2.415846e+07
2026-06-15  64820.20  66117.20  64774.40  66117.20  1.955218e+02  1.281464e+07

[200 rows x 6 columns]

                open      high       low     close        volume      turnover
datetime
2025-11-28  90671.64  97034.36  87147.19  90851.61  4.234554e+02  3.982736e+07
2025-11-29  90851.61  92686.56  85989.45  90827.26  1.169327e+02  1.061767e+07
2025-11-30  90827.26  96200.00  89932.60  95992.31  3.285488e+02  3.061314e+07
2025-12-01  95992.31  96268.64  95767.52  95767.52  5.168455e+01  4.954266e+06
2025-12-02  95767.52  96268.64  78163.90  87713.20  1.847650e+06  1.642927e+11
...              ...       ...       ...       ...           ...           ...
2026-06-11  61825.00  61825.00  61024.10  61755.80  2.858224e+02  1.753588e+07
2026-06-12  61755.80  63730.80  61755.80  63551.20  4.039001e+02  2.545399e+07
2026-06-13  63551.20  64625.20  63431.60  64495.50  4.442794e+02  2.840637e+07
2026-06-14  64495.50  65520.40  63879.20  64820.20  3.735011e+02  2.415846e+07
2026-06-15  64820.20  66117.20  64774.40  66117.20  1.955219e+02  1.281464e+07

[200 rows x 6 columns]

                open      high       low     close        volume      turnover
datetime
2025-11-28  90671.64  97034.36  87147.19  90851.61  4.234554e+02  3.982736e+07
2025-11-29  90851.61  92686.56  85989.45  90827.26  1.169327e+02  1.061767e+07
2025-11-30  90827.26  96200.00  89932.60  95992.31  3.285488e+02  3.061314e+07
2025-12-01  95992.31  96268.64  95767.52  95767.52  5.168455e+01  4.954266e+06
2025-12-02  95767.52  96268.64  78163.90  87713.20  1.847650e+06  1.642927e+11
...              ...       ...       ...       ...           ...           ...
2026-06-11  61825.00  61825.00  61024.10  61755.80  2.858224e+02  1.753588e+07
2026-06-12  61755.80  63730.80  61755.80  63551.20  4.039001e+02  2.545399e+07
2026-06-13  63551.20  64625.20  63431.60  64495.50  4.442794e+02  2.840637e+07
2026-06-14  64495.50  65520.40  63879.20  64820.20  3.735011e+02  2.415846e+07
2026-06-15  64820.20  66117.20  64774.40  66117.20  1.955219e+02  1.281464e+07

[200 rows x 6 columns]

KeyboardInterrupt: